const SERVER_BASE_URL = 'http://localhost:4000';
const GRAPHQL_ENDPOINT = `${SERVER_BASE_URL}/graphql`;

const USERNAMES = {
  MOSHE: 'moshe',
  DAVID: 'david'
};

const TRANSACTION_CATEGORIES = {
  EATING_OUT: 'EATING_OUT',
  GROCERIES: 'GROCERIES',
  VACATION: 'VACATION',
  MEDICAL: 'MEDICAL',
  PUBLIC_TRANSPORTATION: 'PUBLIC_TRANSPORTATION',
  CAR_MAINTENANCE: 'CAR_MAINTENANCE',
  SAVINGS: 'SAVINGS',
  BILLS: 'BILLS',
  ENTERTAINMENT: 'ENTERTAINMENT',
  NO_CATEGORY: 'NO_CATEGORY'
};
module.exports = {
  TRANSACTION_CATEGORIES,
  SERVER_BASE_URL,
  GRAPHQL_ENDPOINT,
  USERNAMES
};